language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t jeffren/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true jeffren/react-test npm test

after_success:
    - docker build -t jeffren/multi-client ./client
    - docker build -t jeffren/multi-nginx ./nginx
    - docker build -t jeffren/multi-server ./server
    - docker build -t jeffren/multi-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push jeffren/multi-client
    - docker push jeffren/multi-nginx
    - docker push jeffren/multi-server
    - docker push jeffren/multi-worker
 